/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\moveee.glb -T -j -M 
Files: raw_assets\moveee.glb [1.09MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\moveee-transformed.glb [132.76KB] (88%)
*/

import { useTexture } from "../utils/ktxLoader";
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/moveee-transformed.glb')

  const texture_1 = useTexture("/textures/moveee_1.webp");
  const texture_2 = useTexture("/textures/moveee_2.webp");
  const texture_3 = useTexture("/textures/moveee_3.webp");
  const texture_4 = useTexture("/textures/moveee_4.webp");

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Moving_Characters_Winter_arm_left_front.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_arm_left_front.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_arm_right_front.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_arm_right_front.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_front_character.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_front_character.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_front_smile.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_front_smile.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_Front_Smile.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_Front_Smile.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_front_smile_face.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_front_smile_face.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_happy_face.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_happy_face.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_head_front.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_head_front.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_left_arm.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_left_arm.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_right_arm.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_right_arm.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_left_foot.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_left_foot.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_right_foot.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_right_foot.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_side.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_side.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_side_face.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_side_face.position} />
      <mesh geometry={nodes.Moving_Characters_Winter_side_face_smile.geometry} material={texture_1} position={nodes.Moving_Characters_Winter_side_face_smile.position} />
      <mesh geometry={nodes.Moving_Characters_Spring_front.geometry} material={texture_1} position={nodes.Moving_Characters_Spring_front.position} />
      <mesh geometry={nodes.Moving_Characters_Spring_side.geometry} material={texture_1} position={nodes.Moving_Characters_Spring_side.position} />
      <mesh geometry={nodes.Moving_Characters_Spring_side_back_wheel.geometry} material={texture_1} position={nodes.Moving_Characters_Spring_side_back_wheel.position} />
      <mesh geometry={nodes.Moving_Characters_Spring_side_face.geometry} material={texture_1} position={nodes.Moving_Characters_Spring_side_face.position} scale={nodes.Moving_Characters_Spring_side_face.scale} />
      <mesh geometry={nodes.Moving_Characters_Spring_side_face_smile.geometry} material={texture_1} position={nodes.Moving_Characters_Spring_side_face_smile.position} />
      <mesh geometry={nodes.Moving_Characters_Spring_side_front_wheel.geometry} material={texture_1} position={nodes.Moving_Characters_Spring_side_front_wheel.position} />
      <mesh geometry={nodes.Moving_Characters_Fall_character.geometry} material={texture_1} position={nodes.Moving_Characters_Fall_character.position} />
      <mesh geometry={nodes.Moving_Characters_Fall_face.geometry} material={texture_1} position={nodes.Moving_Characters_Fall_face.position} />
      <mesh geometry={nodes.Moving_Characters_Fall_left_arm.geometry} material={texture_1} position={nodes.Moving_Characters_Fall_left_arm.position} />
      <mesh geometry={nodes.Moving_Characters_Fall_right_arm.geometry} material={texture_1} position={nodes.Moving_Characters_Fall_right_arm.position} />
      <mesh geometry={nodes.Moving_Characters_Summer_character.geometry} material={texture_1} position={nodes.Moving_Characters_Summer_character.position} />
      <mesh geometry={nodes.Moving_Characters_Summer_character_Wave.geometry} material={texture_1} position={nodes.Moving_Characters_Summer_character_Wave.position} />
      <mesh geometry={nodes.Moving_Characters_Summer_happy_face.geometry} material={texture_1} position={nodes.Moving_Characters_Summer_happy_face.position} />
      <mesh geometry={nodes.Moving_Characters_Summer_left_arm.geometry} material={texture_1} position={nodes.Moving_Characters_Summer_left_arm.position} />
      <mesh geometry={nodes.Moving_Characters_Summer_right_arm.geometry} material={texture_1} position={nodes.Moving_Characters_Summer_right_arm.position} />
    </group>
  )
}

useGLTF.preload('/models/moveee-transformed.glb')
